### ISSUE TITLE
Label is set to default even if provided in CR for valid host

### ISSUE THREAD

**Issue by snehal1797** [metal3-io/hardware-classification-controller#33]
If in the CR, provided the label in key-value pair, and apply the profile with kubectl apply -f Profile.yaml.

Label does not get updated with value provided in the CR to valid host it is set to default.

```
apiVersion: metal3.io/v1alpha1
kind: HardwareClassification
metadata:
  name: hardwareclassification-sample
  namespace: metal3
  labels:
    hardwareclassification-sample: match
spec:
  hardwareCharacteristics:
      cpu:
         minimumCount: 48
         maximumCount: 72
         minimumSpeedMHz: 2600
         maximumSpeedMHz: 3800
      disk:
         minimumCount: 1
         maximumCount: 8
         minimumIndividualSizeGB: 200
         maximumIndividualSizeGB: 3000
      ram:
         minimumSizeGB: 6
         maximumSizeGB: 200
      nic:
         minimumCount: 1
         maximumCount: 12

```

By applying the above Profile CR, the label is set to default which is **matches** for valid hosts.

```
node-50@node50-PowerEdge-R740xd:~$ kubectl get bmh -n metal3  --show-labels
NAME      STATUS   PROVISIONING STATUS   CONSUMER   BMC                                                              HARDWARE PROFILE   ONLINE   ERROR   LABELS
node-49   OK       ready                            redfish://192.168.110.49/redfish/v1/Systems/System.Embedded.1/   unknown            false            hardwareclassification.metal3.io/hardwareclassification-sample=matches
```
